spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL_QUERY:false}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


  h2:
    console.enabled: true
  thymeleaf:
    cache: false

rest-api:
  user-service-properties:
    base-url: ${BASE_URL:http://localhost:9090}
    users-endpoint: /api/users  # Get all users or create a new user
    user-by-id-endpoint: /api/users/{userId}  # Get a specific user by ID
    user-images-endpoint: /api/users/{userId}/images  # Get images for a specific user by ID
  image-service-properties:
    base-url: ${BASE_URL:http://localhost:9090}
    generate-simple-images-endpoint: /api/simpleimagegen
    image-by-id-endpoint: /api/images/{imageId}
    user-images-upload-endpoint: /api/users/{userId}/images/upload
    user-images-edit-endpoint: /api/users/{userId}/images/edit

